name: Belajar CI/CD Pipeline

on:
  push:
    branches:
      - "main"

jobs:
  
  build-and-push:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Auth to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        run: |
          docker buildx create --use
          docker buildx build -t rahadiangg/butcemp-devops:${GITHUB_SHA::7} --push .
  
  deploy-to-gcp:
    runs-on: ubuntu-22.04
    needs:
      - build-and-push

    steps:
      - name: Auth to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with :
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to CloudRun
        run: |
          gcloud run deploy ${GITHUB_REPOSITORY#*/} --image=rahadiangg/butcemp-devops:${GITHUB_SHA::7} \
          --region=asia-southeast2 --memory=128Mi --cpu=1.0 --port=3000 --min-instances=0 --max-instances=3 \
          --allow-unauthenticated --project=${{ secrets.GCP_PROJECT_ID }}