name: Belajar CI/CD Pipeline

on:
  push:
    branches:
      - "main"

jobs:
  
  build-and-push:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Auth to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        run: |
          docker buildx create --use
          docker buildx build -t rahadiangg/butcemp-devops:${GITHUB_SHA::7} --push .